version: '3.8'

services:
  vibe-cms-db:
    image: mongo:latest
    container_name: mongo-vibe-cms
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=vibe-cms
    volumes:
      - ./mongo-keyfile:/etc/mongo-keyfile:ro
    command: ["--replSet", "rs0", "--bind_ip_all", "--keyFile", "/etc/mongo-keyfile"]
  
volumes:
  mongo-vibe-cms_data:
